<?php
/*
 * Implements hook_menu().
 */
function ramp_video_csv_menu() {
  $items = array();

  $items['ramp-vidstory-csv'] = array(
    'title' => 'CSV of video IDs, titles, and URLs',
    'description' => t('CSV of video IDs, titles, and URLs for ramp.'),
    'page callback' => 'ramp_video_csv_generate',
    'access arguments' => array('administer content'),
  );

  return $items;
}

function ramp_video_csv_generate() {

  $results = ramp_video_csv_query();
}

function ramp_video_csv_query() {
  $query = db_select('node', 'n')
    ->fields('n', array('title'))
    ->fields('fw', array('field_wonderbar_video_id_value'))
    ->fields('fua', array('alias'));
  $query->join('field_data_field_wonderbar_video_id', 'fw', 'n.nid = fw.entity_id');
  $query->join('fitpregnancy.url_alias', 'fua', 'concat("node/", fw.entity_id = fua.source');

  $result = $query->execute()->fetchObject();

}
